### ISSUE TITLE
What function remove() is doing ?

### ISSUE THREAD

**Issue by ghost** [jarektkaczyk/laravel-global-scope#3]
I don't know if i understood it right, but seems that the remove() function is removing ALL wheres from the query instead of only the where added for my specific scope.

**Comment by jarektkaczyk** [comment]
Which version of the framework?

**Comment by ghost** [comment]
Laravel 5.0

**Comment by ghost** [comment]
@jarektkaczyk , my doubt was: If calling a specific GlobalScope macro mapped on remove() would remove all previous queries or only that from this specific GlobalScope.

I made some tests and everything is working as expected. Congratulations for the package.
